### ISSUE TITLE
Top distance of QRCode increases according to previous content.

### ISSUE THREAD

**Issue by harguus** [andriyoganp/blue_print_pos#63] opened 2022-05-13 19:16 UTC
First of all congratulations on the package, thank you very much!

I have a problem that according to the amount of content added, the final distance before the QRcode increases directly proportionally, I don't know why but I tested it with your code just by duplicating the last content six times, increasing the amount, you can see in the image the printout left with the code of your example and the right with the same code appended with more texts and there is an increase in the distance between the end of the text and the beginning of the QRcode.
I tested with 3 paper sizes PaperSize.mm50, PaperSize.mm72, PaperSize.mm80 and the same result.

![image](https://user-images.githubusercontent.com/1157913/168374773-3f0d7692-40a8-4744-a1b0-ff0e5fd91b22.png)

Thanks!

**Comment by kechkibet** [comment] 2022-05-15 16:22
Hi,
You have to self host this pr since it is not merged yet: #60 or use my fork:
```
  blue_print_pos:
    git: https://github.com/kechkibet/blue_print_pos.git
```

**Comment by harguus** [comment] 2022-05-15 22:07
> Hi, You have to self host this pr since it is not merged yet: #60 or use my fork:
> 
> ```
>   blue_print_pos:
>     git: https://github.com/kechkibet/blue_print_pos.git
> ```

Okay thank you very much, but why hasn't it been merged yet?

**Comment by harguus** [comment] 2022-05-15 22:21
> Hi, You have to self host this pr since it is not merged yet: #60 or use my fork:
> 
> ```
>   blue_print_pos:
>     git: https://github.com/kechkibet/blue_print_pos.git
> ```

Ok thank you very much solved this problem and the paper size problem.

**Comment by kechkibet** [comment] 2022-05-16 03:59
We are waiting for the owner of the repo to merge.

**Comment by eduardchavez** [comment] 2022-05-29 03:22
I have fixed the problem in my local library... width is ok in webview for android... the problem is the height... I just changed the height and everything is ok now.

**Closed as completed** 2022-05-31 14:40 UTC
